name: asp-net
services:
  users_asp:
    container_name: users_asp
    image: mcr.microsoft.com/dotnet/sdk:8.0
    platform: linux/arm64
    restart: on-failure
    env_file: ../.env
    volumes:
      - ..:/app
      - /app/obj # <- directory won't be mounted
      - /app/bin # <- directory won't be mounted
    working_dir: /app
    command: ["dotnet", "watch","run", -v, "--urls", "http://*:8080"]
    ports:
      - "5981:8080"
    depends_on:
      - postgres_users
  
  postgres_users:
    container_name: postgres_users
    image: postgres:17rc1-alpine
    platform: linux/arm64
    restart: on-failure
    env_file: ../.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    
