services:
  asp_net:
    container_name: asp_net
    image: aspnet
    build: 
      dockerfile: docker/dockerfiles/asp/Dockerfile
      context: ../
      args:
        DATABASE_HOST: ${DATABASE_HOST}
        DATABASE_NAME: ${DATABASE_NAME}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    restart: on-failure
    env_file: ../.env
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: 8080
    expose:
      - 8080
    depends_on:
      postgres_asp_net:
        condition: service_healthy
  
  postgres_asp_net:
    container_name: postgres_asp_net
    image: postgres:17rc1-alpine
    restart: on-failure
    env_file: ../.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 20s
      retries: 3
    
